### PR TITLE
add request to dial callback

### LINKED ISSUE #44: [FR] Dial callback with request information
I want to implement: Use different IP based on different username provided. 
To achieve that, I need to access the `AuthContext` in `socks5.Request`. But currently dial callback doesn't have such parameter. 
My current workaround is to use `socks5.WithConnectHandle` with the entire `func (sf *Server) handleConnect(ctx context.Context, writer io.Writer, request *Request) error` function body copied to my own code, since I can't override or call it directly.

### PR DESCRIPTION
**Pull request by kotori2**
Close #44

### CODE REVIEW

**Comment by kotori2** [comment]
```
> go test ./...
ok      github.com/things-go/go-socks5  (cached)
ok      github.com/things-go/go-socks5/bufferpool       5.189s
ok      github.com/things-go/go-socks5/statute  2.811s
```

**Comment by thinkgos** [comment]
@kotori2  Non-compatible change, suggest add another `dial`(Such as `CustomDial`) to overiwrite default `dial`,  which priority higher than `dial`

**Comment by kotori2** [comment]
> @kotori2 Non-compatible change, suggest add another `dial`(Such as `CustomDial`) to overiwrite default `dial`, which priority higher than `dial`

Yeah that's what I'm thinking about in the first place... 
Gonna make this PR as draft first.

**Comment by kotori2** [comment]
done
```
> go test ./...                
ok      github.com/things-go/go-socks5  1.378s
ok      github.com/things-go/go-socks5/bufferpool       4.424s
ok      github.com/things-go/go-socks5/statute  0.285s
```

**Comment by kotori2** [comment]
Do I need to add test cases for the options?

**Pull request merged**
